ModelApplication/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse

app_name='ModelApplication'
## loof for cross site request forgery
urlpatterns = [
    url(r'^create/$', views.createJob, name='create'),

]

homepage/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse

app_name='homepage'
## loof for cross site request forgery
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^graphs$', views.graphs, name='graphs'),
    

]

itreat/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from ModelApplication import views



urlpatterns = [
    url(r'^', include('ModelApplication.urls')),
    url(r'^', include('homepage.urls')),
    url(r'^admin/', admin.site.urls),
]

homepage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ModelApplication/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
import subprocess
from itreat.settings import BASE_DIR
import os
def createJob(request):


    if request.method == "POST":
        return render(request,"JobSchd/jobfinal_form.html",{})

    command = "Rscript " + BASE_DIR + "/../Model_Application/0_Main.r "
    args = []
    args.append("Project Folder")
    args.append("/home/sumit/MARG/Model_Application/")
    args.append("Halton File")
    args.append("/home/sumit/MARG/Halton_R/haltbrat_vfc101.csv")
    args.append("Input Data")
    args.append("/home/sumit/MARG/Model_Application/az_hhld_vfc_cleaned_final.csv")
    args.append("Output Data")
    #os.remove("/home/sumit/MARG/itreat/static/result/VFC_output.csv")
    args.append("/home/sumit/MARG/itreat/static/result/VFC_output.csv")
    args.append("Seed")
    args.append("1")
    args.append("const|DRVRCNT|NUMADLT|RUR|INCOME1|INCOME5|NUMCHILD|WORK0|WORK2|HSIZE4|SF_Own|Retired|Prop_HH_INC5|Prop_SFHH|AUTO10_Q1")
    args.append("13.03|2.01|0.374|0.867|-1.05|1.325|0.517|-1.513|0.829|-0.669|0.570|-0.878|1.362|0.687|-0.293")
    args.append("const|INCOME1|INCOME2|OWN|HSIZE1|WORK0|POPDEN")
    args.append("1.73|2.37|0.82|-1.65|2.12|1.21|0.00011")
    args.append("const|INCOME1|INCOME2|HSIZE1|Prop_MFHH|WORK2")
    args.append("4.27|1.43|0.96|2.22|0.4|-0.86")
    args.append("const|lif_cyc_1|INCOME3|WORK2|INC1")
    args.append("5.31|0.42|-0.21|-0.34|-0.00034")
    args.append("const|OWN|NUMADLT|WORK3|POPDEN|child_pres|lif_cyc_2")
    args.append("1.69|1.0|0.48|1.02|-0.000088|0.38|0.5")
    args.append("const|INCOME5|lif_cyc_2|HSIZE4|WORK2")
    args.append("1.18|0.72|1.63|1.51|-0.7")
    args.append("const")
    args.append("0.0")
    args.append("0 Vehicles|1 Vehicle Type|2 Vehicle Types|3 Vehicle Types|4 Vehicle Types|5+ Vehicle Types")
    args.append("5|6|7|25|1|4")
    args.append("uno|INCOME1|INCOME4|NUMCHILD|WORK3|Prop_HH_INC5|RATE_AUTO10")
    args.append("-4.542|-0.4|0.164|-0.189|0.173|-1.013|-13.833")
    args.append("uno|WORK2|INCOME2")
    args.append("-5.057|-0.157|0.132")
    args.append("uno|INCOME1|Retired|Prop_HH_INC1")
    args.append("-5.846|0.574|0.202|0.574")
    args.append("uno|NUMCHILD|WORK2|TAZ_den_Q1|RATE_AUTO30")
    args.append("-7.479|0.379|-0.388|-0.307|-1.717")
    args.append("uno|NUMCHILD|TAZ_den_Q1|INCOME2")
    args.append("-7.579|0.331|-0.258|0.269")
    args.append("uno|HHSIZE|TAZ_den_Q1|INCOME1")
    args.append("-8.897|0.138|0.676|0.659")
    args.append("uno|INCOME1|WORK2|Retired|Prop_HH_INC1|RATE_AUTO10|TAZ_den_Q3")
    args.append("-5.815|-1.014|0.169|-0.167|-1.475|-17.83|0.267")
    args.append("uno|INCOME3|HSIZE4|SF_Own|AUTO30_Q1")
    args.append("-7.371|0.257|0.333|0.86|-0.301")
    args.append("uno|INCOME4|child_pres|SF|TAZ_den_Q2")
    args.append("-7.030|0.36|0.313|-0.736|-0.361")
    args.append("uno|INCOME5|HSIZE1|RUR|Prop_SFHH")
    args.append("-7.616|0.244|-0.978|0.239|0.74")
    args.append("uno|RUR|Retired|INCOME4|AUTO10_Q1")
    args.append("-6.583|0.153|-0.353|0.164|-0.229")
    args.append("uno|Prop_HH_INC1|INCOME2|child_pres|AUTO10_Q1")
    args.append("-7.177|1.283|0.345|-0.25|-0.335")
    args.append("uno|RUR|SF_Own|HSIZE1")
    args.append("-8.190|0.705|0.752|-0.567")
    args.append("uno|INCOME1|INCOME2|INCOME3")
    args.append("8.072|0.3|-0.35|-0.15")
    args.append("uno|INCOME1")
    args.append("7.732|0.35")
    args.append("uno|INCOME1")
    args.append("7.806|0.2")
    args.append("uno|INCOME1|INCOME2")
    args.append("10.889|1.55|-0.5")
    args.append("uno|INCOME2|INCOME3")
    args.append("9.810|0.5|1.5")
    args.append("uno|INCOME1|INCOME2|INCOME3")
    args.append("10.949|-0.2|-1.0|3.0")
    args.append("uno|INCOME1|INCOME2")
    args.append("9.233|0.35|-0.65")
    args.append("uno")
    args.append("9.024")
    args.append("uno")
    args.append("9.156")
    args.append("uno")
    args.append("10.134")
    args.append("uno")
    args.append("9.001")
    args.append("uno")
    args.append("9.164")
    args.append("uno|INCOME1|INCOME2|INCOME3")
    args.append("7.507|1.0|-1.0|0.5")
    args.append("Tolerance")
    args.append("0.035")
    args.append("Maximum Iteration")
    args.append("5")
    args.append("const|INCOME1|INCOME2|OWN|HSIZE1|WORK0|POPDEN")
    args.append("0.68|2.093|0.608|-1.430|2.109|1.145|0.00011")
    args.append("const|INCOME1|INCOME2|HSIZE1|Prop_MFHH|child_pres")
    args.append("3.672|1.015|0.646|1.995|0.260|-0.333")
    args.append("const|RUR|INCOME4|INCOME5|HSIZE4|OWN")
    args.append("2.956|0.190|0.353|0.230|0.303|0.983")
    args.append("const|OWN|NUMADLT|WORK3|POPDEN|child_pres")
    args.append("0.0|1.418|0.548|0.460|-0.0001|0.364")
    args.append("const")
    args.append("0.0")
    args.append("const|YCAR0_5|YCAR6_11|INCOME2|INCOME5|WORK3|NUMADLT|HSIZE1|HSIZE4|OWN|MU (Threshold)")
    args.append("-4.494|0.955|1.054|-0.105|0.193|0.409|0.473|-0.417|-0.258|0.285|1.450")
    args.append("const|YVAN6_11|YVAN12|INCOME2|vanmile|TAZ_den_Q3|AUTO10_Q1|EMPDEN")
    args.append("-4.620|1.952|2.572|-0.593|0.00006|0.597|0.867|-0.00023")
    args.append("const|YSUV0_5|YSUV12|NUMADLT|INCOME2|INCOME5|suvmile|WORK3|RATE_TRANSIT30")
    args.append("-3.640|0.905|1.496|0.455|-0.535|0.398|0.00004|-0.459|-34.163")
    args.append("const|YPICK0_5|YPICK6_11|pickmile|INCOME5|WORK3|OWN|empden_per_100|TAZ_den_Q3|AUTO30_Q1")
    args.append("-3.946|0.869|1.016|0.000058|-0.287|0.460|0.808|0.0078|0.299|0.268")
    
    args = list(map(lambda x: "\"" + x + "\"",args))
    
    
    final_args = " ".join(args)
    command += " " + final_args + " " 

    # print command
    process = subprocess.Popen(command,shell=True,stdout=subprocess.PIPE)
    process.wait()
    for line in process.stdout:
            print line
    print process.returncode
    data = {
        'is_success': True
    }
    return JsonResponse(data)

homepage/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


def homepage(request):
    return render(request, 'homepage/home.html', {})

def graphs(request):
    return render(request, 'homepage/graphs.html', {})
# Create your views here.

templates/ModelApplication/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% load static %}
  <title>PopGen</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block layout %}
    <link rel="stylesheet" href="{% static "JobSchd/css/material.min.css" %}" />
    <link rel="stylesheet" href="{% static "JobSchd/css/material-components-web.min.css" %}" />
    <style>

      /* fallback */
      @font-face {
        font-family: 'Material Icons';
        font-style: normal;
        font-weight: 400;
        src: url(https://fonts.gstatic.com/s/materialicons/v41/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2)
        format('woff2');
      }

      .material-icons {
        font-family: 'Material Icons';
        font-weight: normal;
        font-style: normal;
        font-size: 24px;
        line-height: 1;
        letter-spacing: normal;
        text-transform: none;
        display: inline-block;
        white-space: nowrap;
        word-wrap: normal;
        direction: ltr;
        -webkit-font-feature-settings: 'liga';
        -webkit-font-smoothing: antialiased;
      }

    </style>
  {% endblock %}

  {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static "JobSchd/js/material.min.js" %}"></script>
    <script src="{% static "JobSchd/js/material-components-web.min.js" %}"></script>
  {% endblock %}
  
</head>

<body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <a class="mdl-layout-title" href="/" style="text-decoration:none;color:#fff">
      <span class="mdl-layout-title">PopGen</span></a>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
        <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        
        {% if user.is_authenticated %}
          
          <button id="demo-menu-lower-right"
                  class="mdl-button mdl-js-button mdl-button--icon">
                    <i class="material-icons">account_circle</i>
          </button>

          <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu 
                     mdl-js-ripple-effect" style="margin-left:-10px;"
              for="demo-menu-lower-right">
          
            <li class="mdl-menu__item">
              <a href="#" style="text-decoration: none;color:black;display:block">Settings</a>
            </li>

            <li class="mdl-menu__item">
              <a href="{% url 'JobSchd:auth_logout' %}?next={% url 'JobSchd:auth_login' %}" i
                 style="text-decoration:none;color:black;display:block">Logout
              </a>
            </li>

          </ul>

        {% else %}

          <a href="{% url 'JobSchd:auth_login' %}" 
             class="mdl-button mdl-js-button mdl-button--raised 
                    mdl-js-ripple-effect mdl-button--accent">
            <i class="material-icons md-16" style="padding-bottom:7px">lock</i>
            <span>Login</span>
          </a>

        {% endif %}

      </nav>
    </div>
  </header>


  <main class="mdl-layout__content">
    <div class="page-content">
      {% block popgen-content %}
      {% endblock %}
    </div>
  </main>
</div>  


</body>
{% block footer %}
{% endblock %}
</html>

templates/homepage/graphs.html
<!DOCTYPE html>
<html lang="en" class="">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ITREAT</title>
    <link rel="stylesheet" href="{% static "css/vendor.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.red-deep_purple.min.css" />
    <style>

    @font-face {
      font-family: 'icomoon';
      src: url('{% static "fonts/icomoon.eot" %}');
      src: url('{% static "fonts/icomoon.eot" %}') format("embedded-opentype"), url('{% static "fonts/icomoon.ttf" %}') format("truetype"), url('{% static "fonts/icomoon.woff" %}') format("woff"), url('{% static "images/icomoon.svg" %}') format("svg");
      font-weight: normal;
      font-style: normal; }
    </style>
  </head>
  <body data-gr-c-s-loaded="true" data-aos-easing="ease" data-aos-duration="800" data-aos-delay="0">


    <!-- header -->
    <header class="header-sticky header-dark headroom headroom--top headroom--not-bottom" style="background:white;">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark">
          <a class="navbar-brand" href="">
            <img class="navbar-logo navbar-logo-light" src="{% static "images/MARG_black_small.png" %}" alt="Logo">
            <img class="navbar-logo navbar-logo-dark" src="{% static "images/MARG_black_small.png" %}" alt="Logo">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="burger"><span></span></span></button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav align-items-center mr-auto">
              <li class="nav-item">
                <a style="color:black" class="nav-link" href="{% url 'homepage:homepage' %}" role="button">
                  Home
                </a>
              </li>
              <li class="nav-item">
                <a style="color:black" class="nav-link" href="{% url 'homepage:graphs' %}" role="button">
                  Graphs
                </a>
              </li>

            </ul>

            <ul class="navbar-nav align-items-center mr-0">
              <li class="nav-item dropdown">

                <a class="navbar-brand" href="#">
                  <img class="navbar-logo navbar-logo-light" src="{% static "images/asu_fulton_small.jpg" %}" alt="Logo">
                  <img class="navbar-logo navbar-logo-dark" src="{% static "images/asu_fulton_small.jpg" %}" alt="Logo">
                </a>
              </li>

            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- header -->


    <!-- <section class="layers p-0">
      <div class="layers-foreground">
        <div class="container">
          <div class="row align-content-end gutter-0 separated">
            <div class="col-6 align-content-end">
              <div class="row mb-2">
                <div class="col text-center p-5 p-lg-10">
                  <h4 class="display-4 mb-0">Comparison of Household Profiles Based on their Energy Consumption Bin</h4>
                  <!-- <p class="lead"><span class="text-black">Comparison of Household Profiles Based on their Energy Consumption Bin</span></p> --> -->

                  <!-- <img class="card-img" style="max-width:110%;height:250px;" src="{% static "images/graph4.png" %}" alt="Resume">
                </div>
              </div>
            </div>
            <div class="col-6 bg-white">
              <div class="row mb-2">
                <div class="col text-center p-5 p-lg-10">
                  <h4 class="display-4 mb-0">Residential Energy Consumption</h4>
                  <p class="lead"><span class="text-black">Residential Energy Consumption Survey (RECS 2015)</span></p>
                  <ul style="display:inline-block;">
                    <li class="lead" style="text-align:left">Electicity Consumption</li>
                    <li class="lead" style="text-align:left">Natural Gas Consumption</li>
                  </ul>
                  <img class="card-img" style="max-width:110%;height:250px;" src="{% static "images/graph1.png" %}" alt="Resume">



                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </section> -->


            <section class="p-0 separator-top">
              <div class="container">
                <div class="row align-content-end gutter-0 separated">
                  <div class="col-4 align-content-end">
                    <div class="row mb-3">
                      <div class="col text-center p-5 p-lg-5">
                        <h4 class="display-4 mb-0">Comparison of Household Profiles Based on their Energy Consumption Bin</h4>

                      </div>
                    </div>
                  </div>
                  <div class="col-8 bg-white">
                    <div class="row mb-">
                      <div class="col text-center p-10 p-lg-10">
                        <article class="card card-minimal">
                              <img class="card-img" src="{% static "images/graph4.png" %}" alt="Resume">

                            </article>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </section>


            <section class="p-0 separator-top">
              <div class="container">
                <div class="row align-content-end gutter-0 separated">
                  <div class="col-8 bg-white align-content-end">
                    <div class="row mb-">
                      <div class="col text-center p-10 p-lg-10">
                        <article class="card card-minimal">
                              <img class="card-img" src="{% static "images/graph5.png" %}" alt="Resume">

                            </article>
                      </div>
                    </div>
                  </div>
                  <div class="col-4 align-content-end">
                    <div class="row mb-3">
                      <div class="col text-center p-5 p-lg-5">
                        <h4 class="display-4 mb-0">Comparison of Two Zones with Different Energy Consumption Profiles</h4>

                      </div>
                    </div>
                  </div>


                </div>
              </div>
            </section>







    <!-- cta -->
    <section class="bg-dark text-white pb-0 separator-bottom">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-10 text-center">
            <h1></h1>

          </div>

        </div>
      </div>
    </section>
    <!-- / cta -->


    <!-- footer -->
    <footer class="bg-dark text-white">
      <div class="container py-5">
        <div class="row justify-content-between align-items-center">
          <div class="col-md-5 text-center text-md-left">
            <ul class="nav lavalamp"><div class="lavalamp-object ease" style="transition-duration: 0.2s; width: 154.953px; height: 37px; transform: translate(0px, -8px);"></div>

              <!-- <li class="nav-item lavalamp-item" style="z-index: 5; position: relative;">
                <a class="nav-link" href="">Purchase</a>
              </li> -->
            </ul>
          </div>
          <div class="col-md-2 text-center">
            <img class="logo-sm" src="{% static "images/MARG_white_small.png" %}" alt="Logo">
          </div>
          <div class="col-md-5 text-center text-md-right">
            <ul class="socials">
              <li><a href="" class="icon-facebook fs-20"></a></li>
              <li><a href="" class="icon-instagram fs-20"></a></li>
              <li><a href="" class="icon-twitter fs-20"></a></li>
              <li><a href="" class="icon-linkedin fs-20"></a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!-- / footer -->


    <script src="{% static "js/vendor.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script>
    document.querySelector('#spinner1').addEventListener('mdl-componentupgraded', function() {
      this.MaterialProgress.setProgress(44);
    });
  </script>
    <script>
$(document).ready(function() {
    $("#spinner1").hide();
     $("#result").hide();
    $("#calculate").click(function ()
    {
      $("#spinner1").show();
       $.ajax({
            url: "/create/",
            /*data: {
              'jobId': $(this).attr("data-jobid")
            },*/
            dataType: 'json',
            success: function (data) {
              if (data.is_success) {
                var resultMessage = "Successfully deleted job";
                $("#spinner1").hide();
                $("#result").show();

              }
              else {
                var resultMessage = "Error in deleting job";
              }

            }
          });
    });

});
</script>


</body></html>